package com.swd.smk.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.swd.smk.enums.Status;
import lombok.Data;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransactionDTO {
    private Long id;
    private Long memberId;
    private Long packageId;
    private String orderInfo;
    private String bankCode;
    private Double amount;
    private String responseCode; //
    private String transactionDate;
    private Status status;

    // Constructors, getters, and setters can be generated by Lombok
}
