package com.swd.smk.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TransactionStatusDTO {
    private Long id;
    private String transactionId;
    private String status; // e.g., "PENDING", "COMPLETED", "FAILED"
    private String message; // Additional information about the transaction status
    private String timestamp; // Timestamp of the transaction status update

    // Constructors, getters, and setters can be generated by Lombok
}
